env:
  - GO111MODULE=on
  - GOPROXY=https://goproxy.io
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm64
      - arm
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"